# Generated by Django 4.1.4 on 2022-12-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='stocks.location')),
            ],
            options={
                'db_table': 'stocks_company',
            },
        ),
    ]
